### ISSUE TITLE
Usage of annotation processor for EntityFactory - Eclipse

### ISSUE THREAD

**Issue by Namek** [junkdog/artemis-odb#223]
Hi there!
Same problem once again. I try to install annotation processor by downloading it and configuring it exactly as on this Wiki page:
https://github.com/junkdog/artemis-odb/wiki/EntityFactory

I run Eclipse Luna, I have already installed Eclipse Java Development Tools plugin.

I try to develop Eclipse project which requires Maven project which requires artemis-odb and other Maven projects. It doesn't matter to which project I put interfaces extending EntityFactory or into which project I put annotation processor jar in project settings. I tried everything and everywhere. `Window->Show View->Error log` shows nothing about annotations or processing.

Any ideas, help?

**Comment by Namek** [comment]
Oooh, there **is** some error:
```
Exception thrown by Java annotation processor com.artemis.EntityFactoryProcessor@640e8e8c

Stack Trace:
java.lang.ClassCastException: org.eclipse.jdt.internal.compiler.apt.model.TypeVariableImpl cannot be cast to javax.lang.model.type.DeclaredType
	at com.artemis.FactoryModel.validate(FactoryModel.java:67)
	at com.artemis.FactoryModel.<init>(FactoryModel.java:56)
	at com.artemis.EntityFactoryProcessor.process(EntityFactoryProcessor.java:53)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:818)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

but that doesn't help me.

**Comment by junkdog** [comment]
I'll have a look at this after work.

Which version of java are you on? Could you post the factory interface causing the error (could it be a generic member type)?

**Comment by Namek** [comment]
First of all I'm talking about artemis-odb from latest master commit and artemis-odb-processor 0.8.1 (I didn't compile it myself, I downloaded it from [maven repo](http://repo1.maven.org/maven2/net/onedaybeard/artemis/artemis-odb-processor/0.8.1/artemis-odb-processor-0.8.1.jar)).

Tried to do the simplest interface like:
```
public interface OmgArchetype extends EntityFactory<OmgArchetype> { }
```
or
```
public interface OmgArchetype extends EntityFactory { }
```

or with some `@Bind` over the class:
```
@Bind({Position.class})
public interface OmgArchetype extends EntityFactory<OmgArchetype> { }
```
(where `Position` implements `PooledComponent`) or even method with @Bind.

I forgot to mention that the obvious error is runtime error: `java.lang.RuntimeException: com.artemis.utils.reflect.ReflectionException: Class not found com.something.OmgArchetypeImpl` coming from `com.artemis.World.createFactory(World.java:244)`

I've got Java 8u25 64-bit installed on Windows 7 Pro. Previously my project was Java 1.6 but I tried to setup it as 1.8 and didn't help either. What's more I installed IntelliJ IDEA 14 (Community edition), put all my forces into it and even manually setting annotation processor jar didn't help.

Is there any instruction on how to debug this?

**Comment by junkdog** [comment]
Not sure why it didn't work with 1.6. There might be issues running with java 8, but I'm resolving a few compilation errors now (funny how java 8 breaks code). From the initial stacktrace you posted, it looks like java's internals have changed somewhat (in regards to generics perhaps), or javac generates slightly different bytecode - but that seems unlikely.

Most of the current compilation errors seem directly related to changes in how generics works.

**Comment by junkdog** [comment]
Could you try rebuilding artemis from source and try those artifacts instead? Alternatively, I'll push a snapshot from work tomorrow - don't have a key on this one.

**Comment by Namek** [comment]
Previous stacktrace was because I used processor 0.7.2 with latest artemis for a few minutes, so I removed that post. Now I don't get any errors. My guess is that it doesn't find interfaces for it's liking.

I managed to run JUnit tests for artemis-odb-processor. It's green, all's working. Could you tell me how to debug it in real project (even printlns, where to look for them)?

There's one more thing to note - I don't include artemis-odb project, I just include `artemis-odb\artemis\src\main\java` subfolder into my project.

**Comment by Namek** [comment]
I have built jar for processor using `mvn package` inside of `artemis-odb-processor` folder, tried to put it into Eclipse and still no effect. I'd like to **debug it**, fast googling looks like a hard configuration, so printlns would be enough BUT @junkdog where should I look for logs printed by `messenger`? [This topic](http://stackoverflow.com/questions/14490796/where-does-eclipse-print-messages-that-it-outputs-within-an-annotation-processor) didn't help.

**Comment by Namek** [comment]
I created a new very simple project and it still doesn't work. Here's the project, you've been set as collaborator so you can commit.
https://github.com/Namek/artemis_test_project

I wonder what's wrong.

**Comment by junkdog** [comment]
Hmm, I don't recall exactly how I've debugged annotation processors in the past, but I'm pretty sure I set it up as a maven project project and built with `mvnDebug` and then remote debugging through Eclipse. I can look up the details later (running intellij at work, eclipse/intellij at home).

I'll have a look at example project when I return home - or if I can't dislodge myself from the office, I'll look into it tomorrow.

**Comment by junkdog** [comment]
So,  no java source files are generated in the `.apt_generated` folder?

**Comment by Namek** [comment]
Nope. Empty folder.

**Comment by Namek** [comment]
@junkdog Have you checked to whether that sample project works for you?

**Comment by Namek** [comment]
Huh. I managed to setup debugger for annotation processor - thanks to [this tutorial](https://www.youtube.com/watch?v=PjUaHkUsgzo) and googling.

How to debug:
============

0. install `General Purpose Tools\Eclipse Plug-in Development Environment` plugin.
1. on project `artemis-odb-processor` -> right click -> Debug As -> Eclipse Application. It will open second Eclipse process.
2. 2nd Eclipse process: Import test project (a project that will be processed by processor) into it. Setup processor with project by putting jar into `Project options` -> `Java Compiler` -> `Annotation Processing`) - the usual configuration as on [Wiki page](https://github.com/junkdog/artemis-odb/wiki/EntityFactory).
3. Go back to 1st Eclipse process and put some breakpoints in `artemis-odb-processor` code.
4. Go to 2nd Eclipse and change some code. I modify `OmgArchetype`. CTRL+S should pause processor by debugger in 1st instance of Eclipse.


Omg
====

in `EntityFactoryProcessor.java` there's `process` function which begins looks this:

```java
@Override
public boolean process(Set<? extends TypeElement> types, RoundEnvironment roundEnv) {
	if (roundEnv.processingOver() || types.size() == 0)
		return true;

   // the rest of stuff...
}
```

For me it's always returning true in there. `types.size() == 1`

What's even more interesting - it does find my file somewhere:
![entityfactoryprocessor debug](https://cloud.githubusercontent.com/assets/31058/5884638/57cc8418-a360-11e4-99dd-7cbe6d62493f.png)


What is `processingOver()` doing, is it neccessary?

**Comment by Namek** [comment]
How to Build .jar?
==========
How to professionally build that jar? `mvn package` creates .jar but instead this:

![image](https://cloud.githubusercontent.com/assets/31058/5885060/647ef4b0-a366-11e4-8baf-85aa8774bda1.png)

I see this:
![image](https://cloud.githubusercontent.com/assets/31058/5885064/6ab0f8b0-a366-11e4-84e8-7d2210517b9f.png)

I'm able to modify .jar as .zip by copying `META-INF/services` folder containing `javax.annotation.processing.Processor` file containing one line:
```
com.artemis.EntityFactoryProcessor
```

and now it works? Do you do this manually every time or have some script for that?

Bug discovered?
=============
What I have discovered so far, [this flag change](https://github.com/junkdog/artemis-odb/commit/8f8ed4d63cedc23fc0d7e0605212e1bc52f87333#diff-e24c6bc2e2871df863418e65d1f32c1bR171) breaks things for me. When I remove that line my lovely always-wanted `OmgArchetypeImpl.java` file is being generated.

I can make PR for this one but not sure if that's ok, it may break some of your cases (???).

**Comment by junkdog** [comment]
Hehe, yeah, the steps necessary to debug annotation processors through eclipse is really convoluted. Debugging them is much easier when invoked through maven - just issue a mvnDebug and attach to the process.

That's what I would do - unless it works when building with maven... 
```
$ mvn clean package > /dev/null && find target/classes/com/something -name Omg*                                            
target/classes/com/something/OmgArchetype.class
target/classes/com/something/OmgArchetypeImpl.class
```

> Bug discovered?

Definitely looks like it, though I have no idea what causes it. The source link you pasted doesn't highlight any line; could resend link to source in question, thanks.

> What is processingOver() doing, is it neccessary?

If I remember correctly; after generating files, the AP performs an additional check to see if those in turned spawned more compilation units affected by the AP.

> How to Build .jar?

I do it through maven: the pom lists a dependency to 
```xml
		<dependency>
			<groupId>org.kohsuke.metainf-services</groupId>
			<artifactId>metainf-services</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency>
```

Which is another AP (`@MetaInfServices`) for registering AP:s under META-INF/services :)

**Comment by junkdog** [comment]
> I can make PR for this one but not sure if that's ok, it may break some of your cases (???).

Please do - at the very least, it's at least a step in the right direction.

**Comment by Namek** [comment]
> I do it through maven

what command to use? I'm not too much into maven.

> The source link you pasted doesn't highlight any line; could resend link to source in question, thanks.

```java
for (ExecutableElement e : allMembers) {
	FactoryMethod method = factoryMethod(e);
	if (method != null) {
 		methods.add(method);
	} else {
		success = false; //this line breaks things to me
	}
}
```

Removing that line works for me but it may break the intentions of `FactoryModel.factoryMethod()` method. Could you take a look into it?

**Comment by Namek** [comment]
```java
private FactoryMethod factoryMethod(ExecutableElement e) {
	String elementName = e.getSimpleName().toString();
	if (IGNORED_METHODS.contains(elementName)) {
		if (!readCRef(e).isEmpty()) {
			String err = "Invalid method name for factory method";
			messager.printMessage(Kind.WARNING, err, e);
		}
		return null;
	}

...
}
```

Methods from `EntityFactory` interface are tested by that condition. You probably wanted to eleminate methods that have same name in custom interface, e.g. `OmgArchetype` would override `copy` method. I don't do that in my `OmgArchetype` but still method `copy` fall into that conditional check which returns `null` and up above we have `success = false`.

This method is called by `FactoryModel.factoryMethods()` which passes `allMembers`. Those are defined by `ProcessorUtil.componentMethods(TypeElement element)`. It returns 7 methods when I have only one method (called `size`) in my `OmgArchetype`:
```
[
public abstract com.poweracted.components2.OmgArchetype size(float, float) ,
public abstract com.artemis.Entity create() ,
public abstract com.poweracted.components2.OmgArchetype copy() ,
public abstract com.poweracted.components2.OmgArchetype tag(java.lang.String) ,
public abstract com.poweracted.components2.OmgArchetype group(java.lang.String) ,
public transient abstract com.poweracted.components2.OmgArchetype group(java.lang.String, java.lang.String, java.lang.String[]) 
 public transient abstract com.poweracted.components2.OmgArchetype group(java.lang.String, java.lang.String[])
]
```

Now I'm guessing - what were your intentions here? Did you want to return all methods with inherited ones or without? Or with but inherited but without `create`, `copy`, `group`, `tag`?

**Comment by junkdog** [comment]
> > I do it through maven
> 
> what command to use? I'm not too much into maven.

`mvnDebug clean package` or `mvnDebug clean install` - if you want to install the artifacts into your local m2-repo (where all maven artifacts go).

**mvnDebug** waits for a debugger to attach on port 8000 before proceeding with the lifecycle process.

**clean** is what you'd expect, while **package** and **install** builds the jars and the latter also installs them. **install** actually implies **package** too. For some more information, see http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html.

The order of maven's lifecycles matter, ie `mvn package clean` would first execute all lifecycles leading up to **package** before issuing **clean**.

> Now I'm guessing - what were your intentions here?

I don't recall the exact details, but it involved filtering out the predefined methods - in part to avoid naming collisions. Might have been a few more corner cases. I ran it against the current tests and it works fine!

**Comment by Namek** [comment]
Hmm, I only wanted to know how to automatically put that `services` folder into .jar :)

**Comment by junkdog** [comment]
Ah :)

Through maven, it's just `mvn clean package` - maven automatically picks up any jars containing annotation processors, in this case the metainf-services dependency.

**Comment by Namek** [comment]
Wow, weird. `mvn package` doesn't do that, but `mvn clean package` certainly does.

BTW what happened to factory inheritance? Have you found some impossibilities or was it just lack of time/need?

**Comment by junkdog** [comment]
Yeah, annotation processors require a `clean`, usually. Annotation processors are only informed about newly compiled classes - so without the clean, there's no guarantee that the required classes are intercepted by the AP.

**Comment by junkdog** [comment]
> BTW what happened to factory inheritance? Have you found some impossibilities or was it just lack of time/need?

I tried the solution you (I think it was you) suggested, but type erasure and funky type inference kicks in during edge cases, making chaining impossible.

**Comment by Namek** [comment]
> I tried the solution you (I think it was you) suggested, but type erasure and funky type inference kicks in during edge cases, making chaining impossible.

If that was about evil generics usage, then it was @DaanVanYperen's proposal.

**Comment by DaanVanYperen** [comment]
> If you mean that that evil generics usage, then it was @DaanVanYperen's proposal.

HEeeeeeeeeeeeeeyyyyyyyyyy. Heyyyyyyyyyyyy. he.... Heeyyyyyyyyyy.

**Comment by junkdog** [comment]
The Enterprisey Strikes Back!
